### ISSUE TITLE
verwijzing vanuit 3.2.5 naar 3.4 klopt niet (meer)

### ISSUE THREAD

**Issue by NielsHoffmann** [Geonovum/Geo-standaarden-beheerplan#1]
in 3.2.5 staat "paragraaf 3.4 beschreven fasen: Inhoud, Toetsing, Besluitvorming en Implementatie", maar paragraaf 3.4 is 'Adoptie en erkenning'. 
Ik denk dat de verwijzing naar 4.3 moet zijn, maar de fasen komen niet helemaal (meer) overeen...

**Comment by MVS11** [comment]
paragraaf 3.2.5 is vervallen.
