### ISSUE TITLE
Het document gebruikt de verkeerde organisation-config

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/Geo-standaarden-beheerplan#2]
Het document gebruikt een lokale `organisation-config.js` die in deze repository in de `/js/` folder staat. 

Het is de bedoeling dat het document in plaats daarvan de centrale `geonovum-config.js` gebruikt die op tools.geostandaarden.nl staat en die zorgt dat de configuratie van alle Geonovum documenten gelijk is (uitgezonderd documenten in sommmige grote projectenzoals DSO en BRO, die een eigen projectspecifieke organisation-config hebben). 

Concreet betekent dit: in index.html 

`<script class="remove notoc" src="js/organisation-config.js"></script>`

vervangen door

`<script src="https://tools.geostandaarden.nl/respec/config/geonovum-config.js" class="remove"></script>`

**Comment by MVS11** [comment]
regel met verwijzing naar de config.js is aan gepast.
