### ISSUE TITLE
Basisset geostandaarden is gewijzigd

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/Geo-standaarden-beheerplan#3]
De basisset geostandaarden is in 2024 gewijzigd:
- Webservice-profielen voor [Web Feature Service en Web Map Service](https://www.geonovum.nl/geo-standaarden/services) zijn van de lijst afgehaald (deze staan nu op de Aanbevolen lijst)
- OGC API Features part 1 en 2, en OGC API Tiles part 1 zijn aan de basisset geostandaarden toegevoegd. 

In hoofdstuk 1.1 staat nog de oude lijst.

In 4.1 moet dit ook aangepast worden. 

> Nederlandse profielen voor Web Feature Services (WFS) en Web Map Services (WMS)

Kan daar uit de lijst gehaald worden. Er zijn geen Nederlandse profielen op de OGC API standaarden.

**Comment by lvdbrink** [comment]
In 4.2 moet dit ook aangepast worden. NB hier ontbreekt ook GeoPackage, dat wel onderdeel is van de geo-standaarden.

**Comment by MVS11** [comment]
Het overzicht van de basisset geo-standaarden is nu vergelijkbaar met het overzicht op 
https://www.forumstandaardisatie.nl/open-standaarden/geo-standaarden 
Link naar Geopackage aangepast naar de Geonovum website
