### ISSUE TITLE
BZK wordt nog genoemd

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/Geo-standaarden-beheerplan#4]
In paragraaf 2.1 wordt het ministerie van Binnenlandse Zaken en Koninkrijksrelaties nog genoemd. 

Dit moet VRO worden, of misschien kunnen we er iets generieks van maken.

Ook in 2.3 wordt BZK nog genoemd en wellicht verderop in het document ook (niet gecheckt).

**Comment by MVS11** [comment]
alle verwijzingen naar BZK of Binnenlandse Zaken zijn aangepast naar het Ministerie van Volkshuisvesting en Ruimtelijke Ordening
