### ISSUE TITLE
Link naar raamwerk toevoegen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/Geo-standaarden-beheerplan#5]
Het raamwerk van geostandaarden wordt genoemd in paragraaf 2.2. Erachter staat tussen haakjes "link".

Link naar het raamwerk van geostandaarden toevoegen: https://docs.geostandaarden.nl/rwgs/rw/

**Comment by MVS11** [comment]
de zin betreft de klachten over het beheer van de standaarden.. Dit is in het beheerplan toegelicht in paragraaf 6.3. De link is aangebracht naar paragraaf 6.3 ipv naar het raamwerk.
