### ISSUE TITLE
toevoegen "publicatieserver"

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/Geo-standaarden-beheerplan#6]
In paragraaf 4.4 kan een 4e soort publicatieserver worden toegevoegd. Naast register-, definities-, en docs.geostandaarden.nl, hebben we ook `modellen.geostandaarden.nl`. Op https://modellen.geostandaarden.nl/ publiceert Geonovum ontologieën: machineleesbare RDF modellen die zijn afgeleid van informatiemodellen.

(hier staat op dit moment alleen NEN3610 maar ik verwacht dat dit er meer worden)

**Comment by lvdbrink** [comment]
Deze zelfde wijziging ook in paragraaf 6.1 doorvoeren

**Comment by MVS11** [comment]
volgende wijziging doorgevoerd in 4.4 en 6.1:
Ontologieën register https://modellen.geostandaarden.nl/
Publiceren van van ontologieën die zijn afgeleid van informatiemodellen die wij beheren.
